db.movies.insertMany([{
  id: 1,
  title: 'Spiderman (into the spiderverse)',
  releaseYear: 2019,
  duration: '2.1h',
  rating: '7 / 10',
  genre: 'Action',
  director: '',
  writer: '',
  Actors: [],
  plot: '',
  awards: '',
  imageUrl: '/assets/intoTheSpiderverse.jpg',
  cover: '/assets/intoTheSpiderverseC.jpg'
}, {
  id: 1,
  title: 'Spiderman (into the spiderverse)',
  releaseYear: 2019,
  duration: '2.1h',
  rating: '7 / 10',
  genre: 'Action',
  director: '',
  writer: '',
  Actors: [],
  plot: '',
  awards: '',
  imageUrl: '/assets/intoTheSpiderverse.jpg',
  cover: '/assets/intoTheSpiderverseC.jpg'
}, {
  id: 1,
  title: 'Spiderman (into the spiderverse)',
  releaseYear: 2019,
  duration: '2.1h',
  rating: '7 / 10',
  genre: 'Action',
  director: '',
  writer: '',
  Actors: [],
  plot: '',
  awards: '',
  imageUrl: '/assets/intoTheSpiderverse.jpg',
  cover: '/assets/intoTheSpiderverseC.jpg'
}])
